"""Provenance-aware structured exports for recognition candidates."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from xml.etree import ElementTree as ET

from build_recognitions import _public_error

TEI_NS = "http://www.tei-c.org/ns/1.0"
ET.register_namespace("", TEI_NS)


def _text(value: object) -> str:
    return "" if value is None else str(value)


def _optional(value: object) -> str | None:
    value = _text(value).strip()
    return value or None


def _confidence(value: object) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def candidate_json_export(candidate: dict, doc_id: str = "") -> str:
    """Return stable JSON for one candidate and its provenance."""
    error = _public_error(candidate.get("error"))
    text = _text(candidate.get("text"))
    payload = {
        "schema": "agentic-historian/recognition-candidate/v1",
        "doc_id": _text(doc_id),
        "derivation": "selected" if candidate.get("selected") else "candidate",
        "status": "error" if error else "success",
        "engine": _text(candidate.get("engine") or "unknown"),
        "model_id": _optional(candidate.get("model_id")),
        "page": _optional(candidate.get("page")),
        "confidence": _confidence(candidate.get("confidence")),
        "characters": None if error else len(text),
        "text": None if error else text,
        "error": error or None,
    }
    return json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def candidate_tei_xml(candidate: dict, doc_id: str = "") -> str:
    """Return text-only TEI; never invent layout or coordinate markup."""
    tag = lambda name: f"{{{TEI_NS}}}{name}"
    root = ET.Element(tag("TEI"))
    header = ET.SubElement(root, tag("teiHeader"))
    file_desc = ET.SubElement(header, tag("fileDesc"))
    title_stmt = ET.SubElement(file_desc, tag("titleStmt"))
    ET.SubElement(title_stmt, tag("title")).text = (
        f"Recognition candidate for {_text(doc_id) or 'an unspecified document'}"
    )
    publication = ET.SubElement(file_desc, tag("publicationStmt"))
    ET.SubElement(publication, tag("p")).text = "Generated research data; verify against the source."
    source_desc = ET.SubElement(file_desc, tag("sourceDesc"))
    bibl = ET.SubElement(source_desc, tag("bibl"))
    ET.SubElement(bibl, tag("idno"), {"type": "document"}).text = _text(doc_id)
    ET.SubElement(bibl, tag("idno"), {"type": "engine"}).text = _text(candidate.get("engine") or "unknown")
    model = _optional(candidate.get("model_id"))
    page = _optional(candidate.get("page"))
    if model:
        ET.SubElement(bibl, tag("idno"), {"type": "model"}).text = model
    if page:
        ET.SubElement(bibl, tag("biblScope"), {"unit": "page"}).text = page
    revision = ET.SubElement(header, tag("revisionDesc"))
    timestamp = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    ET.SubElement(revision, tag("change"), {"when": timestamp}).text = (
        "Machine-generated by agentic-historian. "
        "Not for citation as verified transcription."
    )
    body = ET.SubElement(ET.SubElement(root, tag("text")), tag("body"))
    text = _text(candidate.get("text"))
    if text:
        ET.SubElement(body, tag("p")).text = text
    return ET.tostring(root, encoding="unicode", xml_declaration=True)
